name: photonic-rv32gc
compiler_exe: riscv64-unknown-elf-gcc
objdump_exe: riscv64-unknown-elf-objdump
ref_model_exe: sail_riscv_sim
udb_config: photonic-rv32gc.yaml
linker_script: link.ld
dut_include_dir: .
